use anyhow::Result;
use sea_orm::sea_query::{
    extension::postgres::Extension, Index, IndexCreateStatement, PostgresQueryBuilder,
};
use sea_orm::{ConnectionTrait, DatabaseConnection, DbBackend, EntityTrait, Schema, Statement};

use super::entities::*;

const CURRENT_SCHEMA_VERSION: i64 = 3;

pub fn latest_version() -> i64 {
    CURRENT_SCHEMA_VERSION
}

async fn ensure_table<E: EntityTrait>(
    db: &DatabaseConnection,
    backend: DbBackend,
    schema: &Schema,
    entity: E,
) -> Result<()> {
    let statement = schema
        .create_table_from_entity(entity)
        .if_not_exists()
        .to_owned();
    db.execute(backend.build(&statement)).await?;
    Ok(())
}

async fn ensure_index(
    db: &DatabaseConnection,
    backend: DbBackend,
    statement: IndexCreateStatement,
) -> Result<()> {
    db.execute(backend.build(&statement)).await?;
    Ok(())
}

async fn ensure_optional_sql(
    db: &DatabaseConnection,
    backend: DbBackend,
    sql: impl Into<String>,
    description: &str,
) -> Result<()> {
    if let Err(error) = db
        .execute(Statement::from_string(backend, sql.into()))
        .await
    {
        tracing::warn!("Skipping optional {}: {}", description, error);
    }
    Ok(())
}

fn sql_string_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn vector_type_has_dimensions(formatted_type: &str) -> bool {
    let normalized = formatted_type.trim().to_ascii_lowercase();
    normalized.starts_with("vector(") || normalized.contains(".vector(")
}

async fn pgvector_column_has_dimensions(
    db: &DatabaseConnection,
    table: &str,
    column: &str,
) -> Result<bool> {
    let sql = format!(
        "SELECT format_type(a.atttypid, a.atttypmod) AS formatted_type \
         FROM pg_attribute a \
         JOIN pg_class c ON c.oid = a.attrelid \
         JOIN pg_namespace n ON n.oid = c.relnamespace \
         WHERE n.nspname = current_schema() \
           AND c.relname = {} \
           AND a.attname = {} \
           AND a.attnum > 0 \
           AND NOT a.attisdropped",
        sql_string_literal(table),
        sql_string_literal(column),
    );
    let row = db
        .query_one(Statement::from_string(DbBackend::Postgres, sql))
        .await?;
    let Some(row) = row else {
        return Ok(false);
    };
    let formatted_type: String = row.try_get("", "formatted_type")?;
    Ok(vector_type_has_dimensions(&formatted_type))
}

async fn ensure_pgvector_hnsw_index(
    db: &DatabaseConnection,
    backend: DbBackend,
    table: &str,
    column: &str,
    sql: impl Into<String>,
    description: &str,
) -> Result<()> {
    if !pgvector_column_has_dimensions(db, table, column).await? {
        tracing::info!(
            "Skipping optional {} because {}.{} uses an unconstrained vector type; HNSW indexes require vector(n)",
            description,
            table,
            column
        );
        return Ok(());
    }
    ensure_optional_sql(db, backend, sql, description).await
}

macro_rules! ensure_table_list {
    ($db:expr, $backend:expr, $schema:expr, [$($entity:path),+ $(,)?]) => {
        $(
            ensure_table($db, $backend, $schema, $entity).await?;
        )+
    };
}

pub async fn run(db: &DatabaseConnection) -> Result<()> {
    if db.get_database_backend() != DbBackend::Postgres {
        anyhow::bail!("storage bootstrap requires a postgres database backend");
    }

    let backend = db.get_database_backend();
    let schema = Schema::new(backend);

    let vector_extension = Extension::create()
        .name("vector")
        .if_not_exists()
        .to_owned();
    db.execute(Statement::from_string(
        backend,
        vector_extension.to_string(PostgresQueryBuilder),
    ))
    .await?;

    ensure_table_list!(
        db,
        backend,
        &schema,
        [
            kv_store::Entity,
            arkpulse_event::Entity,
            browser_session::Entity,
            episode::Entity,
            action::Entity,
            execution_proof::Entity,
            execution_trace::Entity,
            project::Entity,
            task::Entity,
            swarm_agent::Entity,
            swarm_delegation::Entity,
            conversation::Entity,
            message::Entity,
            document::Entity,
            document_chunk::Entity,
            notification::Entity,
            approval_log::Entity,
            automation_run::Entity,
            automation_supervisor_state::Entity,
            watcher::Entity,
            expense::Entity,
            security_log::Entity,
            operational_log::Entity,
            llm_usage::Entity,
            user_preference::Entity,
            user_data_item::Entity,
            knowledge_item::Entity,
            execution_run::Entity,
            run_checkpoint::Entity,
            tool_attempt::Entity,
            experience_run::Entity,
            experience_item::Entity,
            experience_edge::Entity,
            procedural_pattern::Entity,
            learning_candidate::Entity
        ]
    );

    ensure_optional_sql(
        db,
        backend,
        "ALTER TABLE swarm_agents ADD COLUMN IF NOT EXISTS access_scope TEXT NOT NULL DEFAULT '{}'",
        "swarm_agents.access_scope column",
    )
    .await?;

    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_arkpulse_events_timestamp")
            .table(arkpulse_event::Entity)
            .col(arkpulse_event::Column::Timestamp)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_browser_sessions_updated")
            .table(browser_session::Entity)
            .col(browser_session::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_browser_sessions_status_updated")
            .table(browser_session::Entity)
            .col(browser_session::Column::Status)
            .col(browser_session::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_episodes_timestamp")
            .table(episode::Entity)
            .col(episode::Column::Timestamp)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_episodes_project_id")
            .table(episode::Entity)
            .col(episode::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_pgvector_hnsw_index(
        db,
        backend,
        "episodes",
        "embedding",
        "CREATE INDEX IF NOT EXISTS idx_episodes_embedding_hnsw \
         ON episodes USING hnsw (embedding vector_cosine_ops) \
         WHERE embedding IS NOT NULL",
        "episodes pgvector HNSW index",
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_proofs_timestamp")
            .table(execution_proof::Entity)
            .col(execution_proof::Column::Timestamp)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_traces_created")
            .table(execution_trace::Entity)
            .col(execution_trace::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_traces_started")
            .table(execution_trace::Entity)
            .col(execution_trace::Column::StartedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_status")
            .table(task::Entity)
            .col(task::Column::Status)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_scheduled_for")
            .table(task::Entity)
            .col(task::Column::ScheduledFor)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_status_scheduled")
            .table(task::Entity)
            .col(task::Column::Status)
            .col(task::Column::ScheduledFor)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_created_at")
            .table(task::Entity)
            .col(task::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_lease_expires_at")
            .table(task::Entity)
            .col(task::Column::LeaseExpiresAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tasks_next_retry_at")
            .table(task::Entity)
            .col(task::Column::NextRetryAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_swarm_delegations_agent")
            .table(swarm_delegation::Entity)
            .col(swarm_delegation::Column::AgentId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_messages_conversation")
            .table(message::Entity)
            .col(message::Column::ConversationId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_messages_timestamp")
            .table(message::Entity)
            .col(message::Column::Timestamp)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_messages_role_timestamp")
            .table(message::Entity)
            .col(message::Column::Role)
            .col(message::Column::Timestamp)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_conversations_updated")
            .table(conversation::Entity)
            .col(conversation::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_conversations_project")
            .table(conversation::Entity)
            .col(conversation::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_conversations_starred_updated")
            .table(conversation::Entity)
            .col(conversation::Column::Starred)
            .col(conversation::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_documents_project")
            .table(document::Entity)
            .col(document::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_document_chunks_doc")
            .table(document_chunk::Entity)
            .col(document_chunk::Column::DocumentId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_document_chunks_doc_chunk")
            .table(document_chunk::Entity)
            .col(document_chunk::Column::DocumentId)
            .col(document_chunk::Column::ChunkIndex)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_pgvector_hnsw_index(
        db,
        backend,
        "document_chunks",
        "embedding",
        "CREATE INDEX IF NOT EXISTS idx_document_chunks_embedding_hnsw \
         ON document_chunks USING hnsw (embedding vector_cosine_ops) \
         WHERE embedding IS NOT NULL",
        "document chunk pgvector HNSW index",
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_notifications_created")
            .table(notification::Entity)
            .col(notification::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_approval_log_status")
            .table(approval_log::Entity)
            .col(approval_log::Column::Status)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_approval_log_requested")
            .table(approval_log::Entity)
            .col(approval_log::Column::RequestedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_automation_runs_started")
            .table(automation_run::Entity)
            .col(automation_run::Column::StartedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_automation_runs_automation_id")
            .table(automation_run::Entity)
            .col(automation_run::Column::AutomationId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_watchers_status")
            .table(watcher::Entity)
            .col(watcher::Column::Status)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_watchers_created")
            .table(watcher::Entity)
            .col(watcher::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_watchers_next_retry_at")
            .table(watcher::Entity)
            .col(watcher::Column::NextRetryAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_watchers_lease_expires_at")
            .table(watcher::Entity)
            .col(watcher::Column::LeaseExpiresAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_security_logs_created")
            .table(security_log::Entity)
            .col(security_log::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_security_logs_type")
            .table(security_log::Entity)
            .col(security_log::Column::EventType)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_created")
            .table(operational_log::Entity)
            .col(operational_log::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_event_type")
            .table(operational_log::Entity)
            .col(operational_log::Column::EventType)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_event_type_created")
            .table(operational_log::Entity)
            .col(operational_log::Column::EventType)
            .col(operational_log::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_tool_name")
            .table(operational_log::Entity)
            .col(operational_log::Column::ToolName)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_success")
            .table(operational_log::Entity)
            .col(operational_log::Column::Success)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_policy_version")
            .table(operational_log::Entity)
            .col(operational_log::Column::PolicyVersion)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_operational_logs_strategy_version")
            .table(operational_log::Entity)
            .col(operational_log::Column::StrategyVersion)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_llm_usage_created")
            .table(llm_usage::Entity)
            .col(llm_usage::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_llm_usage_model")
            .table(llm_usage::Entity)
            .col(llm_usage::Column::Model)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_llm_usage_provider")
            .table(llm_usage::Entity)
            .col(llm_usage::Column::Provider)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_llm_usage_channel")
            .table(llm_usage::Entity)
            .col(llm_usage::Column::Channel)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_preferences_key")
            .table(user_preference::Entity)
            .col(user_preference::Column::Key)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_preferences_project")
            .table(user_preference::Entity)
            .col(user_preference::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_data_kind")
            .table(user_data_item::Entity)
            .col(user_data_item::Column::Kind)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_data_conversation")
            .table(user_data_item::Entity)
            .col(user_data_item::Column::ConversationId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_data_url")
            .table(user_data_item::Entity)
            .col(user_data_item::Column::Url)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_data_project")
            .table(user_data_item::Entity)
            .col(user_data_item::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_user_data_updated")
            .table(user_data_item::Entity)
            .col(user_data_item::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_knowledge_project")
            .table(knowledge_item::Entity)
            .col(knowledge_item::Column::ProjectId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_knowledge_updated")
            .table(knowledge_item::Entity)
            .col(knowledge_item::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_runs_status")
            .table(execution_run::Entity)
            .col(execution_run::Column::Status)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_runs_stage")
            .table(execution_run::Entity)
            .col(execution_run::Column::CurrentStage)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_runs_updated_at")
            .table(execution_run::Entity)
            .col(execution_run::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_execution_runs_request_id")
            .table(execution_run::Entity)
            .col(execution_run::Column::RequestId)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_run_checkpoints_run_id")
            .table(run_checkpoint::Entity)
            .col(run_checkpoint::Column::RunId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_run_checkpoints_run_sequence")
            .table(run_checkpoint::Entity)
            .col(run_checkpoint::Column::RunId)
            .col(run_checkpoint::Column::SequenceNo)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tool_attempts_run_id")
            .table(tool_attempt::Entity)
            .col(tool_attempt::Column::RunId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_tool_attempts_run_sequence")
            .table(tool_attempt::Entity)
            .col(tool_attempt::Column::RunId)
            .col(tool_attempt::Column::SequenceNo)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_execution_run")
            .table(experience_run::Entity)
            .col(experience_run::Column::ExecutionRunId)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_conversation_created")
            .table(experience_run::Entity)
            .col(experience_run::Column::ConversationId)
            .col(experience_run::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_project_created")
            .table(experience_run::Entity)
            .col(experience_run::Column::ProjectId)
            .col(experience_run::Column::CreatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_scope_state")
            .table(experience_run::Entity)
            .col(experience_run::Column::Scope)
            .col(experience_run::Column::SuccessState)
            .col(experience_run::Column::CorrectionState)
            .col(experience_run::Column::Consolidated)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_intent")
            .table(experience_run::Entity)
            .col(experience_run::Column::IntentKey)
            .col(experience_run::Column::TaskType)
            .col(experience_run::Column::ToolSequenceDigest)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_runs_updated")
            .table(experience_run::Entity)
            .col(experience_run::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_items_scope_key")
            .table(experience_item::Entity)
            .col(experience_item::Column::Kind)
            .col(experience_item::Column::Scope)
            .col(experience_item::Column::ProjectId)
            .col(experience_item::Column::ConversationId)
            .col(experience_item::Column::NormalizedKey)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_items_scope_status")
            .table(experience_item::Entity)
            .col(experience_item::Column::Scope)
            .col(experience_item::Column::Status)
            .col(experience_item::Column::Kind)
            .col(experience_item::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_items_project_status")
            .table(experience_item::Entity)
            .col(experience_item::Column::ProjectId)
            .col(experience_item::Column::Status)
            .col(experience_item::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_items_conversation_status")
            .table(experience_item::Entity)
            .col(experience_item::Column::ConversationId)
            .col(experience_item::Column::Status)
            .col(experience_item::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_edges_source")
            .table(experience_edge::Entity)
            .col(experience_edge::Column::SourceRef)
            .col(experience_edge::Column::SourceKind)
            .col(experience_edge::Column::EdgeType)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_edges_target")
            .table(experience_edge::Entity)
            .col(experience_edge::Column::TargetRef)
            .col(experience_edge::Column::TargetKind)
            .col(experience_edge::Column::EdgeType)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_experience_edges_source_run")
            .table(experience_edge::Entity)
            .col(experience_edge::Column::SourceRunId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_procedural_patterns_scope_key")
            .table(procedural_pattern::Entity)
            .col(procedural_pattern::Column::Scope)
            .col(procedural_pattern::Column::ProjectId)
            .col(procedural_pattern::Column::ConversationId)
            .col(procedural_pattern::Column::IntentKey)
            .col(procedural_pattern::Column::ToolSequenceDigest)
            .unique()
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_procedural_patterns_scope_status")
            .table(procedural_pattern::Entity)
            .col(procedural_pattern::Column::Scope)
            .col(procedural_pattern::Column::Status)
            .col(procedural_pattern::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_procedural_patterns_project_status")
            .table(procedural_pattern::Entity)
            .col(procedural_pattern::Column::ProjectId)
            .col(procedural_pattern::Column::Status)
            .col(procedural_pattern::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_learning_candidates_status")
            .table(learning_candidate::Entity)
            .col(learning_candidate::Column::ApprovalStatus)
            .col(learning_candidate::Column::CandidateType)
            .col(learning_candidate::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_learning_candidates_subject")
            .table(learning_candidate::Entity)
            .col(learning_candidate::Column::SubjectKey)
            .col(learning_candidate::Column::CandidateType)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_learning_candidates_pattern")
            .table(learning_candidate::Entity)
            .col(learning_candidate::Column::PatternId)
            .if_not_exists()
            .to_owned(),
    )
    .await?;
    ensure_index(
        db,
        backend,
        Index::create()
            .name("idx_learning_candidates_project")
            .table(learning_candidate::Entity)
            .col(learning_candidate::Column::ProjectId)
            .col(learning_candidate::Column::ApprovalStatus)
            .col(learning_candidate::Column::UpdatedAt)
            .if_not_exists()
            .to_owned(),
    )
    .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::vector_type_has_dimensions;

    #[test]
    fn vector_type_dimension_detection_requires_explicit_dimensions() {
        assert!(vector_type_has_dimensions("vector(384)"));
        assert!(vector_type_has_dimensions("public.vector(1536)"));
        assert!(!vector_type_has_dimensions("vector"));
        assert!(!vector_type_has_dimensions("text"));
    }
}
